name: Run Java Tests

on:
  push:
    branches: [main]
    paths:
      - 'src/test_case_package/post_tc.java'
  pull_request:
    branches: [main]
    paths:
      - 'src/test_case_package/post_tc.java'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Compile test.java (with dependencies)
        run: |
          mkdir -p lib
          curl -L -o lib/testng.jar https://repo1.maven.org/maven2/org/testng/testng/7.9.0/testng-7.9.0.jar
          curl -L -o lib/jcommander.jar https://repo1.maven.org/maven2/com/beust/jcommander/1.82/jcommander-1.82.jar
          javac -cp "lib/testng.jar:lib/jcommander.jar" src/test_case_package/test.java

      - name: Run TestNG test
        run: |
          java -cp "src:lib/testng.jar:lib/jcommander.jar" org.testng.TestNG -testclass test_case_package.sdf_not_null_test
